
export const getPlaywrightConfig = () => `import { defineConfig, devices } from '@playwright/test';

export default defineConfig({
  testDir: './tests',
  fullyParallel: true,
  forbidOnly: !!process.env.CI,
  retries: process.env.CI ? 2 : 0,
  workers: process.env.CI ? 1 : undefined,
  reporter: 'html',
  use: {
    baseURL: 'http://localhost:3000',
    trace: 'on-first-retry',
  },
  projects: [
    {
      name: 'chromium',
      use: { ...devices['Desktop Chrome'] },
    },
    {
      name: 'firefox',
      use: { ...devices['Desktop Firefox'] },
    },
    {
      name: 'webkit',
      use: { ...devices['Desktop Safari'] },
    },
  ],
});
`;

export const getBasicSpec = () => `import { test, expect } from '@playwright/test';

test('homepage has title', async ({ page }) => {
  await page.goto('/');

  // Expect a title "to contain" a substring.
  // Adjust this regex to match your actual app title
  await expect(page).toHaveTitle(/React|App|Widdx|Dashboard/i);
});

test('main content visible', async ({ page }) => {
  await page.goto('/');
  await expect(page.locator('body')).toBeVisible();
});
`;

export const getE2EReadme = () => `# Playwright E2E Testing Kit

Generated by WIDDX Visual Code Map Engine.

## Setup

1. Install Playwright dependencies in your project root:
   \`\`\`bash
   npm init playwright@latest
   # Select 'tests' as your test directory when prompted to match config
   \`\`\`

   Or manually:
   \`\`\`bash
   npm install -D @playwright/test
   npx playwright install
   \`\`\`

2. Run the tests:
   \`\`\`bash
   npx playwright test
   \`\`\`

3. View the HTML report:
   \`\`\`bash
   npx playwright show-report
   \`\`\`

## Configuration

Check \`playwright.config.ts\` to adjust the \`baseURL\` if your app runs on a port other than 3000.
`;
